osx_image: xcode9.3
language: objective-c
before_install:
        - gem install xcpretty
before_script:
        - set -o pipefail
script:
        - xcodebuild test -project ./Aisatsu.xcodeproj -scheme AisatsuTests -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=11.3,name=iPhone 8' | xcpretty -c
